import type { Molecule } from '../domain/moleculeTypes';

const tetra = [[0, 1, 0], [0.9428, -1 / 3, 0], [-0.4714, -1 / 3, 0.8165], [-0.4714, -1 / 3, -0.8165]] as [number, number, number][];
const linear = [[-1, 0, 0], [1, 0, 0]] as [number, number, number][];
const trigonal = [[1, 0, 0], [-0.5, 0.87, 0], [-0.5, -0.87, 0]] as [number, number, number][];
const octa = [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0], [0, 0, 1], [0, 0, -1]] as [number, number, number][];

export const moleculeCatalog: Molecule[] = [
  { id: 'M01', name: '이산화 탄소', formula: 'CO₂', charge: 0, centralAtom: 'C', atoms: ['O', 'O'], sigmaDomains: 2, lonePairs: 0, electronGeometry: '선형', molecularGeometry: '선형', bondPolarity: '극성 결합', netDipoleClass: 'zero', bondDipoleDirection: 'center-to-outer', idealCoordinates: linear, sourceIds: ['NIST-CO2', 'VSEPR-01'], reviewStatus: '문헌 대조 시작' },
  { id: 'M02', name: '물', formula: 'H₂O', charge: 0, centralAtom: 'O', atoms: ['H', 'H'], sigmaDomains: 2, lonePairs: 2, electronGeometry: '정사면체', molecularGeometry: '굽은형', bondPolarity: '극성 결합', netDipoleClass: 'nonzero', bondDipoleDirection: 'outer-to-center', idealCoordinates: [[-0.78, 0.62, 0], [0.78, 0.62, 0]], sourceIds: ['NIST-H2O', 'VSEPR-01'], reviewStatus: '문헌 대조 시작' },
  { id: 'M03', name: '삼불화 붕소', formula: 'BF₃', charge: 0, centralAtom: 'B', atoms: ['F', 'F', 'F'], sigmaDomains: 3, lonePairs: 0, electronGeometry: '삼각 평면', molecularGeometry: '삼각 평면', bondPolarity: '극성 결합', netDipoleClass: 'zero', bondDipoleDirection: 'center-to-outer', idealCoordinates: trigonal, sourceIds: ['NIST-BF3', 'VSEPR-01'], reviewStatus: '교과 검토 대기' },
  { id: 'M04', name: '암모니아', formula: 'NH₃', charge: 0, centralAtom: 'N', atoms: ['H', 'H', 'H'], sigmaDomains: 3, lonePairs: 1, electronGeometry: '정사면체', molecularGeometry: '삼각뿔형', bondPolarity: '극성 결합', netDipoleClass: 'nonzero', bondDipoleDirection: 'outer-to-center', idealCoordinates: [[0, 0.8165, 0.5774], [-0.7071, -0.4082, 0.5774], [0.7071, -0.4082, 0.5774]], sourceIds: ['NIST-NH3', 'VSEPR-01'], reviewStatus: '교과 검토 대기' },
  { id: 'M05', name: '메테인', formula: 'CH₄', charge: 0, centralAtom: 'C', atoms: ['H', 'H', 'H', 'H'], sigmaDomains: 4, lonePairs: 0, electronGeometry: '정사면체', molecularGeometry: '정사면체', bondPolarity: '약한 결합 극성 모형', netDipoleClass: 'zero', bondDipoleDirection: 'outer-to-center', idealCoordinates: tetra, sourceIds: ['NIST-CH4', 'VSEPR-01'], reviewStatus: '교과 검토 대기' },
  { id: 'M06', name: '사염화 규소', formula: 'SiCl₄', charge: 0, centralAtom: 'Si', atoms: ['Cl', 'Cl', 'Cl', 'Cl'], sigmaDomains: 4, lonePairs: 0, electronGeometry: '정사면체', molecularGeometry: '정사면체', bondPolarity: '극성 결합', netDipoleClass: 'zero', bondDipoleDirection: 'center-to-outer', idealCoordinates: tetra, sourceIds: ['NIST-SiCl4', 'VSEPR-01'], reviewStatus: '교과 검토 대기', condition: '이상화 단량체 모형' },
  { id: 'M07', name: '염화 베릴륨', formula: 'BeCl₂', charge: 0, centralAtom: 'Be', atoms: ['Cl', 'Cl'], sigmaDomains: 2, lonePairs: 0, electronGeometry: '선형', molecularGeometry: '선형', bondPolarity: '극성 결합', netDipoleClass: 'zero', bondDipoleDirection: 'center-to-outer', idealCoordinates: linear, sourceIds: ['NIST-BeCl2', 'VSEPR-01'], reviewStatus: '교과 검토 대기', condition: '기체상 단량체·이상화' },
  { id: 'M08', name: '이산화 황', formula: 'SO₂', charge: 0, centralAtom: 'S', atoms: ['O', 'O'], sigmaDomains: 2, lonePairs: 1, electronGeometry: '삼각 평면', molecularGeometry: '굽은형', bondPolarity: '극성 결합', netDipoleClass: 'nonzero', bondDipoleDirection: 'center-to-outer', idealCoordinates: [[-0.75, 0.64, 0], [0.75, 0.64, 0]], sourceIds: ['NIST-SO2', 'VSEPR-01'], reviewStatus: '교과 검토 대기' },
  { id: 'M09', name: '오염화 인', formula: 'PCl₅', charge: 0, centralAtom: 'P', atoms: ['Cl', 'Cl', 'Cl', 'Cl', 'Cl'], sigmaDomains: 5, lonePairs: 0, electronGeometry: '삼각쌍뿔', molecularGeometry: '삼각쌍뿔', bondPolarity: '극성 결합', netDipoleClass: 'zero', bondDipoleDirection: 'center-to-outer', idealCoordinates: [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -0.5, 0.87], [0, -0.5, -0.87]], sourceIds: ['NIST-PCl5', 'VSEPR-01'], reviewStatus: '교과 검토 대기', condition: '기체상 단량체·이상화' },
  { id: 'M10', name: '육불화 황', formula: 'SF₆', charge: 0, centralAtom: 'S', atoms: ['F', 'F', 'F', 'F', 'F', 'F'], sigmaDomains: 6, lonePairs: 0, electronGeometry: '팔면체', molecularGeometry: '팔면체', bondPolarity: '극성 결합', netDipoleClass: 'zero', bondDipoleDirection: 'center-to-outer', idealCoordinates: octa, sourceIds: ['NIST-SF6', 'VSEPR-01'], reviewStatus: '교과 검토 대기' },
  { id: 'M11', name: '삼불화 염소', formula: 'ClF₃', charge: 0, centralAtom: 'Cl', atoms: ['F', 'F', 'F'], sigmaDomains: 3, lonePairs: 2, electronGeometry: '삼각쌍뿔', molecularGeometry: 'T자형', bondPolarity: '극성 결합', netDipoleClass: 'nonzero', bondDipoleDirection: 'center-to-outer', idealCoordinates: [[-0.85, 0, 0], [0.85, 0, 0], [0, 0.9, 0]], sourceIds: ['NIST-ClF3', 'VSEPR-01'], reviewStatus: '교과 검토 대기' },
  { id: 'M12', name: '사불화 제논', formula: 'XeF₄', charge: 0, centralAtom: 'Xe', atoms: ['F', 'F', 'F', 'F'], sigmaDomains: 4, lonePairs: 2, electronGeometry: '팔면체', molecularGeometry: '평면 정사각형', bondPolarity: '극성 결합', netDipoleClass: 'zero', bondDipoleDirection: 'center-to-outer', idealCoordinates: [[1, 0, 0], [-1, 0, 0], [0, 1, 0], [0, -1, 0]], sourceIds: ['NIST-XeF4', 'VSEPR-01'], reviewStatus: '교과 검토 대기' },
];

export const moleculeById = (id: string) => moleculeCatalog.find((item) => item.id === id) ?? moleculeCatalog[0];
